version: '3'

services: 
  db:
    image: mysql:latest
    restart: always
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes:
      - ./mysql:/var/lib/mysql
